[tool.poetry]
name = "SkyPro-electronics-shop"
version = "0.1.0"
description = ""
authors = ["kirillskyeng <kirill.netreba@skyeng.ru>"]
readme = "README.md"
packages = [{include = "SkyPro-electronics-shop"}]

[tool.poetry.dependencies]
python = "^3.9.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
